import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Navbar from "../components/Navbar/Navbar";

import HomeMain from "../components/HomeMain";

import AboutMauka from "../components/AboutMauka";
import CohortDetails from "../components/CohortDetails";
import Modules from "../components/Modules";

import {
  Box,
  Tag,
  Center,
  Text,
  SimpleGrid,
  Container,
  VStack,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="#0a1e32" minHeight="100vh">
        <Container maxW="container.xl" pt={5}>
          <Navbar />

          <HomeMain />
        </Container>
      </Box>
      <Box minHeight="100vh" bg="#f6f9fe">
        <AboutMauka />
      </Box>
      <Box minHeight="80vh" bg="#f6f9fe">
        <CohortDetails />
      </Box>
      <Box minHeight="100vh" bg="#f6f9fe">
        <Modules />
      </Box>
    </div>
  );
}
